import { expect, test } from '@playwright/test';

const previewReference = 'NOVORA-CB-MOCK-001';

async function expectPreviewBoundaryCopy(page: import('@playwright/test').Page) {
  await expect(page.getByText('Mock preview only', { exact: true })).toBeVisible();
  await expect(page.getByText('No live image provider', { exact: true })).toBeVisible();
  await expect(page.getByText('No real generated image', { exact: true })).toBeVisible();
  await expect(page.getByText('No Supabase or database lookup', { exact: true })).toBeVisible();
  await expect(page.getByText('No GPT, OpenAI, or image-provider work', { exact: true })).toBeVisible();
  await expect(page.getByText('Not CAD', { exact: true })).toBeVisible();
  await expect(page.getByText('Not a quote', { exact: true })).toBeVisible();
  await expect(page.getByText('Not order approval', { exact: true })).toBeVisible();
  await expect(page.getByText('Not payment approval', { exact: true })).toBeVisible();
  await expect(page.getByText('Not production approval', { exact: true })).toBeVisible();
  await expect(page.getByText('Human review is required before customer-facing delivery')).toBeVisible();
  await expect(
    page.getByText('first_preview_ready is separate from approved_for_customer', { exact: true }),
  ).toBeVisible();
}

async function expectNoInternalOrProviderOutput(page: import('@playwright/test').Page) {
  await expect(page.locator('img')).toHaveCount(0);
  await expect(page.getByText('Mock bridge result')).toHaveCount(0);
  await expect(page.getByText('Mock bridge preview data')).toHaveCount(0);
  await expect(page.getByText('Route public_reference')).toHaveCount(0);
  await expect(page.getByText('Mock bridge public_reference')).toHaveCount(0);
  await expect(page.getByText('lifecycle_state')).toHaveCount(0);
  await expect(page.getByText('Image URL')).toHaveCount(0);
  await expect(page.getByText('Provider output')).toHaveCount(0);
  await expect(page.getByText('Provider ID', { exact: false })).toHaveCount(0);
  await expect(page.getByText('provider response', { exact: false })).toHaveCount(0);
  await expect(page.getByText('provider prompt', { exact: false })).toHaveCount(0);
  await expect(page.getByText('raw customer brief', { exact: false })).toHaveCount(0);
  await expect(page.getByText('base64', { exact: false })).toHaveCount(0);
  await expect(page.getByText('data:image', { exact: false })).toHaveCount(0);
  await expect(page.getByText('https://', { exact: false })).toHaveCount(0);
  await expect(page.getByText('Design Spec JSON', { exact: false })).toHaveCount(0);
  await expect(page.getByText('Hand Sketch Instruction', { exact: false })).toHaveCount(0);
  await expect(page.getByText('Prompt chain')).toHaveCount(0);
}

async function expectSafeUnavailable(page: import('@playwright/test').Page) {
  await expect(page.getByRole('heading', { name: 'Customer concept preview' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Preview unavailable' })).toBeVisible();
  await expect(page.getByText('Unavailable', { exact: true })).toBeVisible();
  await expect(page.getByText('This preview is unavailable or the demo link is invalid.')).toBeVisible();
  await expect(page.getByText('This does not mean a real customer record was found.')).toBeVisible();
  await expect(page.getByText('No generated image is available here.')).toBeVisible();
  await expect(page.getByText('No Supabase or database lookup happened', { exact: false })).toBeVisible();
  await expect(page.getByText('no GPT, OpenAI, or image-provider work happened', { exact: false })).toBeVisible();
  await expect(page.getByText('Processing', { exact: true })).toHaveCount(0);
  await expect(page.getByText('Temporarily unavailable', { exact: true })).toHaveCount(0);
  await expect(page.getByText('First preview ready', { exact: true })).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'Mock first concept preview' })).toHaveCount(0);
  await expectPreviewBoundaryCopy(page);
  await expectNoInternalOrProviderOutput(page);
}

test.describe('/design/preview/[public_reference]', () => {
  test('renders the successful hardened mock preview only for the exact ready route', async ({ page }) => {
    await page.goto(`/design/preview/${previewReference}?state=first_preview_ready`);

    await expect(page.getByRole('heading', { name: 'Customer concept preview' })).toBeVisible();
    await expect(page.getByText(previewReference)).toBeVisible();
    await expect(page.getByText('First preview ready', { exact: true })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Mock first concept preview' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Placeholder visual, no generated image' })).toBeVisible();
    await expect(page.getByText('This is a mock preview for MVP flow testing only.')).toBeVisible();
    await expect(page.getByText('It is not generated by a live image provider', { exact: false })).toBeVisible();
    await expect(page.getByText('no real generated image exists here', { exact: false })).toBeVisible();
    await expect(
      page.getByText('This is not customer-safe final delivery. Human review is required before any customer-facing delivery', {
        exact: false,
      }),
    ).toBeVisible();
    await expect(
      page.getByText('first_preview_ready is separate from approved_for_customer', { exact: false }).first(),
    ).toBeVisible();
    await expect(page.getByText('Mock placeholder', { exact: true })).toBeVisible();
    await expect(page.getByText('NOVORA / concept preview sheet / mock only')).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Mock feedback controls' })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Structure issue' })).toBeDisabled();
    await expect(page.getByRole('button', { name: 'Style mismatch' })).toBeDisabled();
    await expect(page.getByText('No feedback is submitted, stored, emailed, or sent to an API from this page.')).toBeVisible();
    await expectPreviewBoundaryCopy(page);
    await expectNoInternalOrProviderOutput(page);
  });

  test('renders safe unavailable for missing state instead of the old processing state', async ({ page }) => {
    await page.goto(`/design/preview/${previewReference}`);

    await expect(page.getByText(previewReference)).toBeVisible();
    await expectSafeUnavailable(page);
  });

  test('renders safe unavailable for unsupported state', async ({ page }) => {
    await page.goto(`/design/preview/${previewReference}?state=unexpected_state`);

    await expect(page.getByText(previewReference)).toBeVisible();
    await expectSafeUnavailable(page);
  });

  test('keeps approved_for_customer separate from first_preview_ready', async ({ page }) => {
    await page.goto(`/design/preview/${previewReference}?state=approved_for_customer`);

    await expect(page.getByText(previewReference)).toBeVisible();
    await expectSafeUnavailable(page);
    await expect(
      page.getByText('first_preview_ready is separate from approved_for_customer', { exact: true }),
    ).toBeVisible();
    await expect(page.getByText('customer-safe final delivery', { exact: false })).toHaveCount(1);
  });

  test('renders safe unavailable for unsupported public reference', async ({ page }) => {
    await page.goto('/design/preview/NOVORA-CB-NOT-REAL?state=first_preview_ready');

    await expect(page.getByText('NOVORA-CB-NOT-REAL')).toBeVisible();
    await expectSafeUnavailable(page);
  });

  test('collapses older non-ready lifecycle states to safe unavailable', async ({ page }) => {
    const staleLifecycleStates = [
      'processing',
      'generation_delayed',
      'generation_failed',
      'preview_unavailable',
      'feedback_submitted',
      'human_followup_needed',
    ] as const;

    for (const state of staleLifecycleStates) {
      await page.goto(`/design/preview/${previewReference}?state=${state}`);

      await expect(page.getByText(previewReference)).toBeVisible();
      await expectSafeUnavailable(page);
    }
  });
});
